### ISSUE TITLE
not working when Redmine is in subfolder?

### ISSUE THREAD

**Issue by ianchan** [mentel/redmine-favorite-locations#1]
Our Redmine is located within a subfolder. The favorite location block appears in right column of our pages but there is no form to add pages as favorites. When I check the Network tab in Chrome's Developer Tools, I see that the favorite_locations?no_edit_favorite_locations=true is not found b/c the URL points to the domain not subfolder.

In other words - 
https://our.side.org/favorite_locations?no_edit_favorite_locations=true is 404
Instead it should be 
https://our.side.org/redmine-folder/favorite_locations?no_edit_favorite_locations=true

Your help in resolving this issue is greatly appreciated.

**Comment by arosenfeld-mentel** [comment]
Fixed with #3
